controllers/SiteController.php
<?php

namespace app\controllers;

//use app\components\NodeLogger;
use app\components\RoleAccessBehaviour;
use app\models\Action;
use app\models\RegisterForm;
use app\models\User;
use Yii;
use yii\db\Expression;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{

    public function behaviors()
    {
        //NodeLogger::sendLog(Action::getAccess($this->id));
        //apply role_action table for privilege (doesn't apply to super admin)
        return Action::getAccess($this->id);
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionProfile()
    {
        $model = User::find()->where(["id"=>Yii::$app->user->id])->one();
        $oldMd5Password = $model->password;
        $oldPhotoUrl = $model->photo_url;

        $model->password = "";

        if ($model->load($_POST)){
            //password
            if($model->password != ""){
                $model->password = md5($model->password);
            }else{
                $model->password = $oldMd5Password;
            }

            # get the uploaded file instance
            $image = UploadedFile::getInstance($model, 'photo_url');
            if ($image != NULL) {
                # store the source file name
                $model->photo_url = $image->name;
                $arr = explode(".", $image->name);
                $extension = end($arr);

                # generate a unique file name
                $model->photo_url = Yii::$app->security->generateRandomString() . ".{$extension}";

                # the path to save file
                $path = Yii::getAlias("@app/web/uploads/") . $model->photo_url;
                $image->saveAs($path);
            }else{
                $model->photo_url = $oldPhotoUrl;
            }

            if($model->save()){
                Yii::$app->session->addFlash("success", "Profile successfully updated.");
            }else{
                Yii::$app->session->addFlash("danger", "Profile cannot updated.");
            }
            return $this->redirect(["profile"]);
        }
        return $this->render('profile', [
            'model' => $model,
        ]);
    }

    public function actionRegister()
    {
        $this->layout = "main-login";

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new RegisterForm();
        if ($model->load(Yii::$app->request->post()) && $model->register()) {
            Yii::$app->session->addFlash("success", "Register success, please login");
            return $this->redirect(["site/login"]);
        }
        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionLogin()
    {
        $this->layout = "main-login";

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            //log last login column
            $user = Yii::$app->user->identity;
            $user->last_login = new Expression("NOW()");
            $user->save();

            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        //log last login column
        $user = Yii::$app->user->identity;
        $user->last_logout = new Expression("NOW()");
        $user->save();

        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<!-- Main content -->
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

views/site/footer.php
<div class="row warnadasar">
    <div class="col-md-6 col-sm-12 bigpadding">
        <h3>Kontak</h3>
        <p style="padding-top: 10px;padding-left: 5px">
            Indoarta Citra Media<br>
            Sukolilo Park Regency C-22<br>
            Keputih, Sukolilo, Surabaya<br>
            Telepon: 0811-333-525<br>
            Email : febri@indoarta.co.id<br>
        </p>
    </div>
    <div class="col-md-6 col-sm-12 bigpadding">
        <h3>Related Sites</h3>
        <p>
        <ul>
            <li><a href="http://indoarta.co.id/">Indoarta Citra Media</a></li>
        </ul>
        </p>
    </div>
</div>
<div class="row warnagelap">
    <div class="col-md-5 col-sm-12 bigpadding">
        2016 &copy; Indoarta Citra Media
    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Beranda';
?>
<div id="map" style="height: 400px"></div>
<script>
    function initMap() {
        //-7.2907939,112.7893436
        var myLatLng = {lat: -7.2766438, lng: 112.794941};

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: myLatLng,
            scrollwheel: false,
            mapTypeControl: false,
        });

        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'PENS'
        });

        var infowindow = new google.maps.InfoWindow({
            content: 'Politeknik Elektronika Negeri Surabaya'
        });
        infowindow.open(map, marker);
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCaLTRspMDvX9TfZSXtDWCyxYoBIBAZPWA&callback=initMap">
</script>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];

?>

<div class="container-fluid warnadasar">
    <div class="row">
        <div class="col-md-5 col-sm-12">
            <?= Html::img(["css/logo.png"], ["class" => "img-responsive"]) ?>
        </div>
    </div>
</div>


<div class=" container-fluid">
    <div class="row" style="background: #fff">
        <div class="col-md-9 col-sm-12">
            <?= $this->render('slider') ?>
        </div>
        <div class="col-md-3 col-sm-12">
            <div>
                <h3>Login | <?= Html::a("Daftar", ["site/register"]) ?></h3>
                <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>
                <?= $form
                    ->field($model, 'username', $fieldOptions1)
                    ->label(false)
                    ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>
                <?= $form
                    ->field($model, 'password', $fieldOptions2)
                    ->label(false)
                    ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>
                <div class="row">
                    <div class="col-xs-12">
                        <?= Html::submitButton("<i class='fa fa-lock'></i> LOGIN", ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
                    </div>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>
<?= $this->render('footer') ?>

views/site/profile.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\User $model
 */

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="giiant-crud">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2><?= $model->name ?></h2>
        </div>

        <div class="panel-body">

            <div class="user-form">

                <?php $form = ActiveForm::begin([
                        'id' => 'User',
                        'layout' => 'horizontal',
                        'enableClientValidation' => false,
                        'errorSummaryCssClass' => 'error-summary alert alert-error',
                        'options' => ['enctype' => 'multipart/form-data'],
                    ]
                );
                ?>

                <div class="">
                    <?php $this->beginBlock('main'); ?>

                    <p>
                        <input type="tel" hidden /> <!-- disable chrome autofill -->
                        <?= $form->field($model, 'password')->passwordInput(['maxlength' => true, 'autocomplete' => "off"]) ?>
                        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                        <?= $form->field($model, 'photo_url')->widget(\kartik\file\FileInput::className(), [
                            'options' => ['accept' => 'image/*'],
                            'pluginOptions' => [
                                'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'gif', 'bmp'],
                                'maxFileSize' => 250,
                            ],
                        ]) ?>
                        <?php
                        if($model->photo_url != null){
                            ?>
                            <div class="form-group">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <?= Html::img(["uploads/".$model->photo_url], ["width"=>"150px"]); ?>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </p>
                    <?php $this->endBlock(); ?>

                    <?=
                    Tabs::widget(
                        [
                            'encodeLabels' => false,
                            'items' => [[
                                'label' => 'User',
                                'content' => $this->blocks['main'],
                                'active' => true,
                            ],]
                        ]
                    );
                    ?>
                    <hr/>
                    <?php echo $form->errorSummary($model); ?>
                    <?= Html::submitButton(
                        '<span class="glyphicon glyphicon-check"></span> ' .
                        ($model->isNewRecord ? 'Create' : 'Save'),
                        [
                            'id' => 'save-' . $model->formName(),
                            'class' => 'btn btn-success'
                        ]
                    );
                    ?>

                    <?php ActiveForm::end(); ?>

                </div>

            </div>

        </div>

    </div>

</div>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\LoginForm */

$this->title = 'Register';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-user form-control-feedback'></span>"
];


$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions3 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

    <div class="container-fluid warnadasar">
        <div class="row">
            <div class="col-md-5 col-sm-12">
                <?= Html::img(["css/logo.png"], ["class" => "img-responsive"]) ?>
            </div>
        </div>
    </div>


    <div class=" container-fluid">
        <div class="row" style="background: #fff">
            <div class="col-md-9 col-sm-12">
                <?= $this->render('slider') ?>
            </div>
            <div class="col-md-3 col-sm-12">
                <div>
                    <h3><?= Html::a("Login", ["site/login"]) ?> | Daftar</h3>
                    <?php $form = ActiveForm::begin(['id' => 'register-form', 'enableClientValidation' => false]); ?>
                    <?= $form
                        ->field($model, 'name', $fieldOptions1)
                        ->label(false)
                        ->textInput(['placeholder' => $model->getAttributeLabel('name')]) ?>
                    <?= $form
                        ->field($model, 'username', $fieldOptions2)
                        ->label(false)
                        ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>
                    <?= $form
                        ->field($model, 'password', $fieldOptions3)
                        ->label(false)
                        ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>
                    <div class="row">
                        <div class="col-xs-12">
                            <?= Html::submitButton("<i class='fa fa-lock'></i> DAFTAR", ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
                        </div>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
<?= $this->render('footer') ?>

views/site/slider.php
<?php
/* @var $this yii\web\View */
?>

<div class="master-slider ms-skin-default" id="masterslider">
    <div class="ms-slide">
        <img src="<?= \yii\helpers\Url::to(["css/blank.gif"]) ?>" data-src="<?= \yii\helpers\Url::to(["css/slider.png"]) ?>" alt="lorem ipsum dolor sit"/>
    </div>
    <div class="ms-slide">
        <img src="<?= \yii\helpers\Url::to(["css/blank.gif"]) ?>" data-src="<?= \yii\helpers\Url::to(["css/slider.png"]) ?>" alt="lorem ipsum dolor sit"/>
    </div>
    <div class="ms-slide">
        <img src="<?= \yii\helpers\Url::to(["css/blank.gif"]) ?>" data-src="<?= \yii\helpers\Url::to(["css/slider.png"]) ?>" alt="lorem ipsum dolor sit"/>
    </div>
</div>

<?php $this->registerJs('

var slider = new MasterSlider();
slider.setup(\'masterslider\' , {
    width:800,
    height:430,
    fullwidth:true,
    space:5,
    view:"basic",
    autoHeight:true
});
slider.control(\'arrows\');
slider.control(\'bullets\' , {autohide:false});
slider.control(\'scrollbar\' , {dir:\'h\'});


'); ?>